### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by AhmedThahir** [sakshamssr/Stock-Market-Simulator#3]
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/dashboard

Django Version: 5.0.4
Python Version: 3.11.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'app1']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/ahmedthahir/anaconda3/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedthahir/anaconda3/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahmedthahir/Investa/app1/views.py", line 131, in dashboard
    data = user_a(requests)
           ^^^^^^^^^^^^^^^^
  File "/Users/ahmedthahir/Investa/app1/views.py", line 100, in user_a
    stockname=user.stockbuy.keys()
              ^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /dashboard
Exception Value: 'list' object has no attribute 'keys'
```

**Comment by sakshamssr** [comment]
✅ Fix Implemented
The issue has been resolved.
Default storage is now set to use a dictionary for stock data instead of lists.

Please create a new user and log in again to verify the fix.
